// Workaround needed for nexus publishing bug
// version and group must be specified in the root project
// https://github.com/gradle-nexus/publish-plugin/issues/310
version = projectVersion
group = 'io.github.gpc'

def publishedProjects = [
        'grails-postgresql-extensions-core',
        'grails-postgresql-extensions',
]

ext.pgextDevelopers = [
        ilopmar: 'Iván López',
        alotor: 'Alonso Torres',
        mattfeury: 'Matt Feury',
        alvarosanchez: 'Alvaro Sanchez-Mariscal',
        aeischeid: 'Aaron Eischeid',
        mkobel: 'Moritz Kobel',
        manuelvio: 'Manuel Unno Vio',
        bameda: 'David Barragán Merino',
        nobeans: 'Yasuharu Nakano',
        burtbeckwith: 'Burt Beckwith',
        timic: 'Timur Salyakhutdinov',
        zlegein: 'Zach Legein',
        tmarthal: 'Tom Marthaler',
        pabloalba: 'Pablo Alba',
        cornercase: 'Eamon Doyle',
        poundex: 'Adam Pounder',
        gregopet: 'Gregor Petrin',
        unknown: 'Tom Potts',
        sabst: 'Sabst',
        donbeave: 'Alexey Zhokov',
        jglapa: 'Jakub Glapa',
        jamesdh: 'James Hardwick',
        butters16: 'John Keith',
        erichelgeson: 'Eric Helgeson',
        albertop19: 'albertop19',
        gtors: 'Andrey T',
        matrei: 'Mattias Reichel',
        sbglasius: 'Søren Berg Glasius'
]

subprojects {

    repositories {
        mavenCentral()
        maven { url = 'https://repo.grails.org/grails/restricted' }
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex('org[.]apache[.](grails|groovy).*', '.*', '.*-SNAPSHOT')
            }
        }
    }

    if (name in publishedProjects) {
        // This has to be applied here in the root project due to the nexus plugin requirements
        apply plugin: 'org.apache.grails.gradle.grails-publish'
    }
}
