// Workaround needed for nexus publishing bug
// version and group must be specified in the root project
// https://github.com/gradle-nexus/publish-plugin/issues/310
version = projectVersion
group = 'this.will.be.overridden'

subprojects {

    repositories {
        mavenCentral()
        maven { url = 'https://repo.grails.org/grails/restricted' }
        maven {
            url = 'https://repository.apache.org/content/groups/snapshots'
            content {
                includeVersionByRegex('org[.]apache[.](grails|groovy).*', '.*', '.*-SNAPSHOT')
            }
        }
    }

    if (name == 'grails-postgresql-extensions') {
        // This has to be applied here in the root project due to the nexus plugin requirements
        apply plugin: 'org.apache.grails.gradle.grails-publish'
    }
}
