projectVersion=8.0.0

grailsVersion=7.0.0
javaVersion=17

hibernate5Version=5.6.15.Final

# This prevents the Grails Gradle Plugin from unnecessarily excluding slf4j-simple in the generated POMs
# https://github.com/grails/grails-gradle-plugin/issues/222
slf4jPreventExclusion=true

org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
